  jdbc:
    initialize-schema: always
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/springbatch
      username: root
      password: KM@852147154
#    batch:
#      jdbc:
#        initialize-schema: always
    batch:
      job:
        enabled: false